### ISSUE TITLE
Change website paths

### ISSUE THREAD

**Issue by huytt621** [upenu/upenu.github.io#60]
The exec team wants to simplify the website paths. In particular, they want to get rid of some unnecessary nesting (e.g. https://upe.berkeley.edu/profdev/services/ -> https://upe.berkeley.edu/services). For this ticket, please look through the website and make suggestions for different paths in the comments (make sure to @huytt621 so I get a notification). Once approved, feel free to make the changes in the codebase.

**Comment by cynic01** [comment]
@huytt621 The website paths I think could be shortened are:
https://upe.berkeley.edu/profdev/services/ -> https://upe.berkeley.edu/services/
https://upe.berkeley.edu/about/history/ -> https://upe.berkeley.edu/history/

Also these three could be consolidated into a People page (or just put them under a common url):
https://upe.berkeley.edu/profdev/oh-holders/ -> https://upe.berkeley.edu/oh-holders/
https://upe.berkeley.edu/about/officers/ -> https://upe.berkeley.edu/officers/
https://upe.berkeley.edu/about/family/ -> https://upe.berkeley.edu/family/

**Comment by cynic01** [comment]
And I also think the history page and the about page (main page) could be merged, they talk about the same stuff

**Comment by huytt621** [comment]
@cynic01 Looks good to me! Feel free to make those changes

**Comment by huytt621** [comment]
Also make sure you pull the latest changes before you start since I did end up removing the history page for the same reason you mentioned.
